.PHONY: help download_model

help:
	@echo "Available targets:"
	@echo "  download_model        Download the local E5 model using download_e5_model.py"


# Download local E5 model
download_model:
	python3 download_e5_model.py
